# Generated by Django 2.1.7 on 2019-04-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
