# Generated by Django 2.2.1 on 2019-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190527_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='love',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
